services:
  db:
    image: mysql:8.0
    ports:
      - "3333:3306"
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-plaravel" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  php:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      XDEBUG_MODE: "coverage"
    healthcheck:
      test: [ "CMD", "pgrep", "php-fpm" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - .:/var/www/html/:consistent
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini:ro
    depends_on:
      - db
